[package]
name = "oxide-auth"
version = "0.4.2"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"

description = "A OAuth2 server library, for actix, gotham or other libraries, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"

autoexamples = false


[dependencies]
base64 = "0.9"
chrono = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ring = "0.13"
rmp-serde = "^0.13"
url = "1.7"
bytes = "0.4.11"

actix = { version = "0.7.9", optional = true }
actix-web = { version = "0.7.17", optional = true }
mime = { version = "0.3.13", optional = true }
futures = { version = "0.1", optional = true }
iron = { version = "0.6", optional = true }
rocket = { version = "0.4.0", optional = true }
rouille = { version = "3.0", optional = true }
router = { version = "0.6", optional = true }
serde_urlencoded = { version = "0.5.1", optional = true }
urlencoded = { version = "^0.6", optional = true }

# Gotham, not in used right now
# gotham = { version = "^0.2", optional = true }
# gotham_derive = { version = "^0.2", optional = true }
# hyper = { version = "^0.11", optional = true }

[features]
default = ["actix-frontend"]
actix-frontend = ["actix", "actix-web", "futures", "serde_urlencoded"]
iron-frontend = ["iron", "router", "serde_urlencoded"]
rouille-frontend = ["rouille", "serde_urlencoded"]
rocket-frontend = ["rocket", "serde_urlencoded"]

# These frontends are disabled for now:
# gotham-frontend = ["gotham", "gotham_derive", "hyper", "mime", "futures", "serde_urlencoded"]

[dev-dependencies]
reqwest = "^0.9"

[[example]]
name = "actix"
required-features = ["actix-frontend"]

[[example]]
name = "rouille"
required-features = ["rouille-frontend"]

[[example]]
name = "rocket"
required-features = ["rocket-frontend"]

# [[example]]
# name = "authorization_gotham"
# required-features = ["gotham-frontend"]

[[example]]
name = "iron"
required-features = ["iron-frontend"]

[package.metadata.docs.rs]
features = ["actix-frontend", "iron-frontend", "rocket-frontend", "rouille-frontend"]
